### ISSUE TITLE
部署中文语言包时发生500错误

### ISSUE THREAD

**Issue by RoyceNi** [jsthon/flarum-ext-simplified-chinese#11]
我在Hostinger空间部署Flarum Beta 4时，试图安装中文语言包。
可当我将文件上传到目录并启用插件的时候，发生了一个错误，返回如下：

> PHP Fatal error:Call to undefined method Flarum\Event\ConfigureLocales::loadLanguagePackFrom() in $in /home/nitrous/code/public_html/extensions/flarum-ext-simplified-chinese/bootstrap.php on line 8

此时，我**删除了上传的语言包插件**，网站恢复访问。
由于是bootstarp.php引发的错误，**我将英文插件的bootstarp覆盖了中文插件，发现可以正常使用。**
不知道是不是引用的问题。
我不知道其中的原因，可否解答一下？

**Comment by jsthon** [comment]
需要赋予插件目录755文件权限

**Comment by coffiner** [comment]
可直接把中午翻译包里面的yml替换到英文版本下，直接通过
重新在后台安装即可。
