### ISSUE TITLE
下载到 扩展包目录extensions下面还是报错

### ISSUE THREAD

**Issue by galenzx** [jsthon/flarum-ext-simplified-chinese#12]
下载下来 文件夹怎么命名呢？
flarum-chinses
还是不用改 直接解压flarum-ext-simplified-chinese-master

但是下来之后在后台安装这个扩展 失败 报错

**Comment by jsthon** [comment]
flarum-ext-simplified-chinese

当前最新代码适配beta.5

如需早期版本请使用[发行版本](https://github.com/jsthon/flarum-ext-simplified-chinese/releases)

**Comment by galenzx** [comment]
我就是用的最新 flarum版本

**Comment by galenzx** [comment]
改名了还是不行报错 报错500 @jsthon

**Comment by galenzx** [comment]
发型版本问题

**Comment by galenzx** [comment]
已经解决

**Comment by coffiner** [comment]
@zachdary 可以直接替换把yml替换到英文版本下，测试已经通过了
