### ISSUE TITLE
“登入-登出”的翻译 是否符合用户习惯

### ISSUE THREAD

**Issue by veekxt** [jsthon/flarum-ext-simplified-chinese#13]
虽然英文log in和log out对应地翻译为 登入和登出 似乎很合适（？），但是大陆地区不这么翻译，也不符合多数简体用户的习惯（参考大陆网站及各网站简体中文版）。

建议使用“登录 - 退出”

**Comment by jsthon** [comment]
http://discuss.flarum.org.cn/d/156

抱歉，我暂时无法满足所有人的想法。

不过，一段时间后，我将会根据这些问题，重新调整出更舒适措辞。
